### PR TITLE
Add configuration for ready-to-go downloaded sample

### PR DESCRIPTION
**Pull request by archieag**

### CODE REVIEW

**Comment by archieag** [comment]
do-not-merge

**Review by jmprieur — APPROVED** [review]
LGTM.
Thanks @archieag

**Comment by archieag** [comment]
@jmprieur Code config can be merged. Please merge. 

#sign-off

**Comment by jmprieur** [comment]
Thanks @archieag 
merged.
cc: @hamiltonha 
cc: @DarylThayil @sameerag

**Pull request merged**
